### ISSUE TITLE
Mistake in Consumer docs

### ISSUE THREAD

**Issue by icefoxen** [jonhoo/faktory-rs#11]
https://docs.rs/faktory/0.9.2/faktory/struct.Consumer.html#connecting-to-faktory says:

> Faktory suggests using the FAKTORY_PROVIDER and FAKTORY_URL environment variables (see their docs for more information) with localhost:7419 as the fallback default. If you want this behavior, use ConsumerBuilder::connect_env.

`ConsumerBuilder::connect_env` doesn't exist, and its functionality seems to have been subsumed by `ConsumerBuilder::connect`.

**Comment by jonhoo** [comment]
Good catch! Fix (being) published in 0.9.3!
