### ISSUE TITLE
Consumer::run_to_completion() has an unused type parameter?

### ISSUE THREAD

**Issue by icefoxen** [jonhoo/faktory-rs#12]
`Consumer::run_to_completion()` has the following signature:

> fn run_to_completion<Q, U>(self, queues: &[Q]) -> !

The `U` parameter appears to be used for nothing, and defining it to be anything when I call the function seems to change nothing; without an explicit definition for it the call does not compile.

**Comment by jonhoo** [comment]
Huh, yeah, you're right. That seems like an oversight from a long time ago. I wonder if this is a leftover from back when I tried to be clever about accepting anything that can be treated as a `&[Q]`. Want to submit a PR removing it?

**Comment by jonhoo** [comment]
Fixed in #14.
