### ISSUE TITLE
Missing function Producer::connect_env

### ISSUE THREAD

**Issue by blankenshipz** [jonhoo/faktory-rs#17]
Somewhat like #11 the `Producer::connect_env` does not seem to exist but is mentioned in the documentation; unlike #11 this functionality does not seem to exist elsewhere?

**Comment by jonhoo** [comment]
@blankenshipz Does `Producer::connect(None)` not do what you want (specifically, it uses `FAKTORY_PROVIDER` and `FAKTORY_URL` from the enviornment)? You're right that the docs should be updated to not talk about `connect_env` anymore though!
