### ISSUE TITLE
Use isize instead of usize for retry Job property

### ISSUE THREAD

**Issue by Fred-JulieDesk** [jonhoo/faktory-rs#20]
Hello,

as per Faktory docs, we need to send a rety value of -1 for not retrying jobs but keep them in the dead queue for later inspection, as of now, the use of the usize type for the retry property prevent this.

Can you change it to isize so we are able to send negative numbers to the Faktory server?

Thanks,

**Comment by jonhoo** [comment]
Ah, yes, you're right, that's a good point. Could you submit a PR that makes that change? Sadly, this will be a backwards-incompatible change, so we'd have to release a new major version, but maybe that's okay.

**Comment by Fred-JulieDesk** [comment]
Done, #21

**Comment by kitified** [comment]
I'm going through issues and since #21 was accepted, closing this issue!
