### ISSUE TITLE
Open to replacing `failure` with `thiserror`?

### ISSUE THREAD

**Issue by kitified** [jonhoo/faktory-rs#27]
Hey there! I'm starting a new project using this library.

Now that `failure` [is deprecated](https://github.com/rust-lang-deprecated/failure#failure---a-new-error-management-story), and the ecosystem is moving towards a system where libraries report implementations of `Error`, would you be open to a PR replacing usage of `failure` with proper `Error` implementations?

**Comment by jonhoo** [comment]
Absolutely!

**Comment by kitified** [comment]
@jonhoo awesome, thanks! I put in a PR here: https://github.com/jonhoo/faktory-rs/pull/28

**Comment by kitified** [comment]
@jonhoo also, I was looking over the other issues and saw this:

> I'm also looking for maintainers if anyone using Faktory on a regular basis is looking to step up to the plate

My company is building out at least one large-ish rust system that uses faktory for job dispatch (and we already use faktory heavily in other languages), so I will likely be trying to upstream multiple PRs as part of that over the coming weeks/months. 

I'm open to stepping up to the plate here- happy to talk more about what that'd look like for you and how I can help!

**Comment by jonhoo** [comment]
@kitified That'd be amazing! I've added you as a maintainer of the GitHub project. I'll hold off on the crates.io release privileges for the time being, but as you ramp up on the project I'm happy to share that too :) Even though you have permissions now, please do keep submitting PRs and I'll do my best to give reviews in a timely fashion!

**Comment by kitified** [comment]
Sounds great, will do!
