### ISSUE TITLE
Removing/clearing the queue programmatically

### ISSUE THREAD

**Issue by rbozan** [jonhoo/faktory-rs#56]
It is not clear to me how to remove the queue in Rust using the library. Basically, the equivalent of the Clear button in the WebUI :

![image](https://github.com/jonhoo/faktory-rs/assets/7997154/d4807200-1916-438f-b33f-1412bea73c0a)

**Comment by jonhoo** [comment]
cc @rustworthy in case you know

**Comment by rustworthy** [comment]
@rbozan thanks for pointing at that. Indeed, not all queue control actions are supported right now. We support pause/resume queues by names, and plan to cover the rest of functionality:
- pause/resume all queues;
- clear (effectively, _remove_) all queues;
- clear (effectively, _remove_) queues by names;

Planning to deliver that after the ongoing work on the switch to async is finished. But a PR will be much appreciated!
---
For reference:

The relevant Faktory server [code](https://github.com/contribsys/faktory/blob/main/server/commands.go#L45-L75)
The corresponding [section](https://github.com/jonhoo/faktory-rs/blob/main/src/proto/single/cmd.rs#L263-L295) in our bindings.

---
cc @jonhoo

**Comment by jonhoo** [comment]
Closed by https://github.com/jonhoo/faktory-rs/pull/59
