### ISSUE TITLE
Support spawning a worker pool with `run`

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/faktory-rs#6]
Currently, `run` (and by extension, `run_to_completion`) only spawns a single worker thread. While users are free to manage threads themselves, this is still unfortunate as it duplicates heartbeats, and makes error handling more complex (e.g., `run_to_completion` returning on one thread would kill the others without allowing them to fail jobs).

This should be fixed by instead spinning up a worker pool of configurable size to handle jobs.

**Comment by KMarshland** [comment]
For those who came to this issue looking how to run multiple workers, it is documented here: https://docs.rs/faktory/0.12.1/faktory/struct.Consumer.html#concurrency

tl;dr:
```rust
consumer_builder.workers(10);
```
