### ISSUE TITLE
Use error type instead of using catch all failure::Error in Producer::con

### ISSUE THREAD

**Issue by wezm** [jonhoo/faktory-rs#8]
Per the [failure guidance](https://boats.gitlab.io/failure/use-error.html#caveats-on-this-pattern) the `failure::Error` type is typically only recommended when prototyping or for "applications" that won't handle the error. It would be better to define a custom error type and 'derive Fail' for it. 

I see there are some parts of the code using a custom error type but others are falling back on Error.

If this sounds reasonable I'm happy to make this change.

**Comment by jonhoo** [comment]
For the various methods on `Producer`, I completely agree that a custom error type would be useful. For `Consumer::run*` it's less clear that the user of the library can do anything useful on error, so I'm less concerned. Happy to take a look at a PR!

**Comment by jonhoo** [comment]
@wezm still want to take a stab at this too? I'd be happy to review and merge!

**Comment by jonhoo** [comment]
@wezm still want to take a stab at this too? I'd be happy to review and merge!
